[svc-ansible@rchanstwr01v mrss_tenable]$ ansible-playbook -i inventory install_tenable.yml

PLAY [Set OS Version Fact] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

TASK [Set OS version fact] ***********************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

PLAY [Install Tenable Tools] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

TASK [tenable : Set OS version fact] *************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

TASK [tenable : Debug OS facts] ******************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com] => {
    "msg": "ansible_os_family=RedHat, os_version=7"
}

TASK [tenable : Fail if not RHEL 7, 8, or 9] *****************************************************************************************************************************************************************************************************
fatal: [rchdtsr01v.vzbi.com]: FAILED! => {"changed": false, "msg": "This role only supports RHEL 7, 8, and RHEL 9"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
rchdtsr01v.vzbi.com        : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
[cssopMRSS@abrdmdcspba2q2v ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[cssopMRSS@abrdmdcspba2q2v ~]$ 



##
[svc-ansible@rchanstwr01v mrss_tenable]$ ansible-playbook -i inventory install_tenable.yml

PLAY [Set OS Version Fact] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [abrdmdcspba2q2v.vzbi.com]

TASK [Set OS version fact] ***********************************************************************************************************************************************************************************************************************
ok: [abrdmdcspba2q2v.vzbi.com]

PLAY [Install Tenable Tools] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Debug OS facts] ******************************************************************************************************************************************************************************************************************
ok: [abrdmdcspba2q2v.vzbi.com] => {
    "msg": "ansible_os_family=RedHat, ansible_distribution_major_version=7"
}

TASK [tenable : Fail if not RHEL 7, 8, or 9] *****************************************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Check if NessusAgent is installed] ***********************************************************************************************************************************************************************************************
ok: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Get version of NessusAgent if installed] *****************************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Display version of NessusAgent] **************************************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Display upgrade version] *********************************************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Copy the NessusAgent RPM from local files directory] *****************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Upgrade NessusAgent using the RPM file] ******************************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Remove NessusAgent RPM from /tmp after installation] *****************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

TASK [tenable : Restart NessusAgent service] *****************************************************************************************************************************************************************************************************
skipping: [abrdmdcspba2q2v.vzbi.com]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
abrdmdcspba2q2v.vzbi.com   : ok=5    changed=0    unreachable=0    failed=0    skipped=8    rescued=0    ignored=0   

[svc-ansible@rchanstwr01v mrss_tenable]$ 
###



---
- name: "Install Tenable Tools"
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: tenable
  tags:
    - tenable


####
---
- name: Debug OS facts
  debug:
    msg: "ansible_os_family={{ ansible_os_family }}, ansible_distribution_major_version={{ ansible_distribution_major_version }}"

- name: Set OS version fact
  set_fact:
    os_version: "{{ ansible_distribution_major_version | int }}"

- name: Fail if not RHEL 7, 8, or 9
  fail:
    msg: "This role only supports RHEL 7, 8, and RHEL 9"
  when: ansible_os_family != 'RedHat' or os_version not in [7, 8, 9]

- name: Check if NessusAgent is installed
  command: rpm -q NessusAgent
  register: nessus_installed
  failed_when: nessus_installed.rc not in [0,1]
  changed_when: false

- name: Display message if Nessus Agent is already installed
  debug:
    msg: "Nessus Agent is already installed on {{ inventory_hostname }}"
  when: nessus_installed.rc == 0

- name: Create directories for nessus agent
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /apps/tools/nessus_agent
    - /opt/nessus_agent

- name: Add bind mount to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/apps/tools/nessus_agent /opt/nessus_agent none defaults,bind 0 0"
    state: present

- name: Mount the bind mount
  become: true
  command: mount --bind /apps/tools/nessus_agent /opt/nessus_agent

- name: Create a directory in /tmp/tenable if it does not exist
  become: true
  ansible.builtin.file:
    path: "/tmp/tenable"
    state: directory
    owner: "svc-ansible"
    group: "svc-ansible"
    mode: "0775"

- block:
    - name: Copy Nessus Agent RPM to /tmp
      copy:
        src: "files/NessusAgent-10.7.3-el{{ os_version }}.x86_64.rpm"
        dest: "/tmp/tenable/NessusAgent-10.7.3-el{{ os_version }}.x86_64.rpm"
        mode: '0755'

    - name: Install Nessus Agent RPM
      # Use yum for RHEL 7 compatibility. On RHEL 8/9, yum redirects to dnf internally.
      yum:
        name: "/tmp/tenable/NessusAgent-10.7.3-el{{ os_version }}.x86_64.rpm"
        state: present
        disable_gpg_check: yes

    - name: Remove Nessus Agent RPM from /tmp after installation
      file:
        path: "/tmp/tenable/NessusAgent-10.7.3-el{{ os_version }}.x86_64.rpm"
        state: absent

  when: nessus_installed.rc != 0

- name: Start Nessus Agent service
  ansible.builtin.service:
    name: nessusagent
    state: started

- name: Link Nessus Agent to manager
  become: true
  ansible.builtin.shell: >
    /opt/nessus_agent/sbin/nessuscli agent link
    --key=fead1abb54958281b1ae15d5c1180d2319004ee327df785498d6b111aa12a25f
    --groups=VGMN-VZB
    --proxy-host=vz-idnproxy.vzbi.com
    --proxy-port=80
    --host=sensor.cloud.tenable.com
    --port=443
  register: link_result
  ignore_errors: yes

- name: Check Nessus Agent status
  ansible.builtin.shell: /opt/nessus_agent/sbin/nessuscli agent status
  register: agent_status

- name: Display Nessus Agent status
  ansible.builtin.debug:
    var: agent_status.stdout_lines
