[svc-ansible@rchanstwr01v mrss_tenable]$ ansible-playbook -i inventory install_tenable.yml

PLAY [Set OS Version Fact] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

TASK [Set OS version fact] ***********************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

PLAY [Install Tenable Tools] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

TASK [tenable : Set OS version fact] *************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com]

TASK [tenable : Debug OS facts] ******************************************************************************************************************************************************************************************************************
ok: [rchdtsr01v.vzbi.com] => {
    "msg": "ansible_os_family=RedHat, os_version=7"
}

TASK [tenable : Fail if not RHEL 7, 8, or 9] *****************************************************************************************************************************************************************************************************
fatal: [rchdtsr01v.vzbi.com]: FAILED! => {"changed": false, "msg": "This role only supports RHEL 7, 8, and RHEL 9"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
rchdtsr01v.vzbi.com        : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
[cssopMRSS@abrdmdcspba2q2v ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[cssopMRSS@abrdmdcspba2q2v ~]$ 

























---
- name: "Install Tenable Tools"
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: tenable
  tags:
    - tenable




---
- name: Debug OS facts
  debug:
    msg: "ansible_os_family={{ ansible_os_family }}, ansible_distribution_major_version={{ ansible_distribution_major_version }}"

- name: Fail if not RHEL 7, 8, or 9
  fail:
    msg: "This role only supports RHEL 7, 8, and RHEL 9"
  when: ansible_os_family != 'RedHat' or (ansible_distribution_major_version|int not in [7,8,9])

- name: Check if NessusAgent is installed
  command: rpm -q NessusAgent
  register: nessus_installed
  failed_when: nessus_installed.rc not in [0,1]
  changed_when: false

- name: Get version of NessusAgent if installed
  command: rpm -q --queryformat '%{VERSION}' NessusAgent
  when: nessus_installed.rc == 0
  register: nessus_version
  changed_when: false

- name: Display version of NessusAgent
  debug:
    msg: "Installed version of NessusAgent is {{ nessus_version.stdout }}"
  when: nessus_installed.rc == 0

- name: Display upgrade version
  debug:
    msg: "Upgrading NessusAgent to version 10.6.4"
  when: nessus_installed.rc == 0 and nessus_version.stdout != "10.6.4"

- name: Upgrade NessusAgent if not already the desired version
  block:
    - name: Copy the NessusAgent RPM from local files directory
      copy:
        src: "roles/upgrade_nessus_agent/files/NessusAgent-10.6.4-el{{ ansible_distribution_major_version }}.x86_64.rpm"
        dest: "/tmp/tenable/NessusAgent-10.6.4-el{{ ansible_distribution_major_version }}.x86_64.rpm"
      when: nessus_installed.rc == 0 and nessus_version.stdout != "10.6.4"

    - name: Upgrade NessusAgent using the RPM file
      yum:
        name: "/tmp/tenable/NessusAgent-10.6.4-el{{ ansible_distribution_major_version }}.x86_64.rpm"
        state: latest
        disable_gpg_check: yes
      when: nessus_installed.rc == 0 and nessus_version.stdout != "10.6.4"

    - name: Remove NessusAgent RPM from /tmp after installation
      file:
        path: "/tmp/tenable/NessusAgent-10.6.4-el{{ ansible_distribution_major_version }}.x86_64.rpm"
        state: absent
      when: nessus_installed.rc == 0 and nessus_version.stdout != "10.6.4"

    - name: Restart NessusAgent service
      service:
        name: nessusagent
        state: restarted
      when: nessus_installed.rc == 0 and nessus_version.stdout != "10.6.4"
