---
- name: Ensure NessusAgent is at desired version on RHEL 7, 8, or 9
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    desired_version: "10.6.4"

  tasks:
    - name: Set OS version fact
      set_fact:
        os_version: "{{ ansible_distribution_major_version | int }}"

    - name: Fail if not RHEL 7, 8, or 9
      fail:
        msg: "This role only supports RHEL 7, RHEL 8, and RHEL 9"
      when: ansible_distribution != 'RedHat' or os_version not in [7, 8, 9]

    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Check if NessusAgent is installed
      set_fact:
        nessus_installed: "{{ 'NessusAgent' in ansible_facts.packages }}"
        current_version: "{{ ansible_facts.packages['NessusAgent'][0].version if nessus_installed else None }}"

    - name: Debug NessusAgent current version
      debug:
        msg: "Installed version of NessusAgent: {{ current_version }}"
      when: nessus_installed

    - name: Debug desired version of NessusAgent
      debug:
        msg: "Upgrading NessusAgent to version {{ desired_version }}"
      when: nessus_installed and current_version is defined and current_version != desired_version

    - name: Copy the NessusAgent RPM if upgrade is needed
      copy:
        src: "roles/upgrade_nessus_agent/files/NessusAgent-{{ desired_version }}-el{{ os_version }}.x86_64.rpm"
        dest: "/tmp/tenable/NessusAgent-{{ desired_version }}-el{{ os_version }}.x86_64.rpm"
      when: nessus_installed and current_version != desired_version

    - name: Install or upgrade NessusAgent
      package:
        name: "/tmp/tenable/NessusAgent-{{ desired_version }}-el{{ os_version }}.x86_64.rpm"
        state: present
      when: nessus_installed and current_version != desired_version

    - name: Remove NessusAgent RPM from /tmp after installation
      file:
        path: "/tmp/tenable/NessusAgent-{{ desired_version }}-el{{ os_version }}.x86_64.rpm"
        state: absent
      when: nessus_installed and current_version != desired_version

    - name: Restart NessusAgent service if upgraded
      service:
        name: nessusagent
        state: restarted
      when: nessus_installed and current_version != desired_version
