---
- name: Check and Upgrade NessusAgent
  hosts: all
  become: yes  # Ensure you have sudo privileges

  tasks:
    - name: Check if OS is RHEL 7, RHEL 8, or RHEL 9
      block:
        - name: Set OS version fact
          set_fact:
            os_version: "{{ ansible_distribution_major_version | int }}"

        - name: Fail if not RHEL 7, 8, or 9
          fail:
            msg: "This playbook only supports RHEL 7, RHEL 8, and RHEL 9"
          when: ansible_distribution != 'RedHat' and os_version not in [7, 8, 9]

    - name: Check if NessusAgent is installed
      command: rpm -q NessusAgent
      register: nessus_installed
      failed_when: nessus_installed.rc not in [0,1]
      changed_when: false

    - name: Get version of NessusAgent if installed
      command: rpm -q --queryformat '%{VERSION}' NessusAgent
      when: nessus_installed.rc == 0
      register: nessus_version
      changed_when: false

    - name: Display version of NessusAgent
      debug:
        msg: "Installed version of NessusAgent is {{ nessus_version.stdout }}"
      when: nessus_installed.rc == 0

    - name: Upgrade NessusAgent if it is installed
      block:
        - name: Copy the NessusAgent RPM from local files directory
          copy:
            src: "{{ playbook_dir }}/files/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
            dest: "/tmp/tenable/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"

        - name: Upgrade NessusAgent using the RPM file
          yum:
            name: "/tmp/tenable/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
            state: latest
            disable_gpg_check: yes

        - name: Remove NessusAgent RPM from /tmp after installation
          file:
            path: "/tmp/tenable/NessusAgent-10.5.1-el{{ os_version }}.x86_64.rpm"
            state: absent

      when: nessus_installed.rc == 0 and nessus_version.stdout != "10.5.1"

    - name: Restart NessusAgent service
      ansible.builtin.service:
        name: nessusagent
        state: restarted
      when: nessus_installed.rc == 0
